name: Package mailgo test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Install golangci-lint
      run: github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - name: Run staticcheck
      run: staticcheck ./...
    - name: Run golangci-lint
      run: golangci-lint run
